# [Template] Builds and publishes UPM .tgz packages
parameters:
  projectRoot: $(Get-Location)
  outputDirectory: $(Build.ArtifactStagingDirectory)\build\upm\output
  version: $(MRTKVersion)
  buildNumber: $(Build.BuildNumber)
  excludeBuildNumber: 0

variables:
- name: previewVersion
  value: ""

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.18.0'

- powershell: |
    $previewVersion = ${{ parameters.buildNumber }}.Substring(4)
    echo "##vso[task.setvariable variable=previewVersion"]$previewVersion

- ${{ if eq(parameters.excludeBuildNumber, 0) }}:
  - task: PowerShell@2
    displayName: 'Build PREVIEW UPM packages'
    inputs:
      targetType: filePath
      filePath: ./scripts/packaging/createupmpackages.ps1
      arguments: >
        -ProjectRoot ${{ parameters.projectRoot }}
        -OutputDirectory ${{ parameters.outputDirectory }}
        -Version ${{ parameters.version }}
        -BuildNumber $(previewVersion)

- ${{ if eq(parameters.excludeBuildNumber, 1) }}:
  - task: PowerShell@2
    displayName: 'Build OFFICIAL UPM packages'
    inputs:
      targetType: filePath
      filePath: ./scripts/packaging/createupmpackages.ps1
      arguments: >
        -ProjectRoot ${{ parameters.projectRoot }}
        -OutputDirectory ${{ parameters.outputDirectory }}
        -Version ${{ parameters.version }}
        -BuildNumber $(parameters.previewVersion)
        -ExcludeBuildNumber

- task: PublishBuildArtifacts@1
  displayName: 'Publish UPM packages'
  inputs:
    PathtoPublish: ${{ parameters.outputDirectory }}
    ArtifactName: 'mrtk-upm'
