
parameters:
  UnityVersion: ""

steps:
- powershell: |
   # Find unity.exe as Start-UnityEditor currently doesn't support arbitrary parameters
   $editor = Get-ChildItem ${Env:${{ parameters.UnityVersion }}} -Filter 'Unity.exe' -Recurse | Select-Object -First 1 -ExpandProperty FullName
   
   $outDir = "$(Build.ArtifactStagingDirectory)\build"
   $logFile = New-Item -Path "$outDir\build\profileSerializationValidation.log" -ItemType File -Force
   
   $proc = Start-Process -FilePath "$editor" -ArgumentList "-projectPath $(Get-Location) -batchmode -executeMethod Microsoft.MixedReality.Toolkit.Tools.Build.ProfileSerializationValidator.CommandLineValidate -logFile $($logFile.FullName) -nographics -quit" -PassThru
   $ljob = Start-Job -ScriptBlock { param($log) Get-Content "$log" -Wait } -ArgumentList $logFile.FullName
   
   while (-not $proc.HasExited -and $ljob.HasMoreData)
   {
       Receive-Job $ljob
       Start-Sleep -Milliseconds 200
   }
   Receive-Job $ljob
   
   Stop-Job $ljob
   
   Remove-Job $ljob
   Stop-Process $proc

   $unityLogFileName = '$(Build.ArtifactStagingDirectory)\build\build\profileSerializationValidation.log'
   If (Test-Path $unityLogFileName)
   {
      Write-Output '====================================================='
      Write-Output '           Begin Unity Player Log                    '
      Write-Output '====================================================='

      Get-Content $unityLogFileName

      Write-Output '====================================================='
      Write-Output '           End Unity Player Log                      '
      Write-Output '====================================================='
   }
   Else
   {
      Write-Output 'Unity Player Log missing!'
   }
   if ($proc.ExitCode -ne 0)
   {
       exit $proc.ExitCode
   }
  displayName: 'Validate Profile Serialization'
