# Build for PR validation.

variables:
  Unity2018Version: Unity2018.4.6f1
  Unity2019Version: Unity2019.2.0f1
  MRTKVersion: 2.4.0

jobs:
- job: PRValidation
  timeoutInMinutes: 90
  pool:
    name: On-Prem Unity
    demands:
    - Unity2018.4.6f1
    - COG-UnityCache-WUS2-01
    - SDK_18362 -equals TRUE
  steps:
  - template: templates/common.yml
    parameters:
      packagingEnabled: true
      packagePublishing: false
  - template: templates/end.yml
  - template: templates/compliance.yml
