# Build for PR validation.
# Contains two parallel jobs, one of which builds the code and runs a linter
# to validate common errors, another which runs the tests.

variables:
- template: config/settings.yml

jobs:
- job: PRValidationBuild
  timeoutInMinutes: 20
  pool:
    name: On-Prem Unity
    demands:
    - Unity2018.4.6f1
    - COG-UnityCache-WUS2-01
    - SDK_18362 -equals TRUE
  steps:
  - template: templates/common.yml
    parameters:
      # For mrtk_pr builds, don't build all flavors to reduce the amount of time
      # taken for each validation run. With this configuration, only the Standalone
      # configuration is built.
      # Note that all of the flavors are still built during the rolling CI.
      # If there are failures in rolling CI in any of these tasks, we should re-enable
      # the specific flavors below that are experiencing failures in CI (for example,
      # if we're actively working on features that have a lot of churn on underlying
      # WMR APIs, buildUWPArm would be a good candidate to re-enable)
      buildStandalone: true
      buildUWPX86: false
      buildUWPArm: false
      buildUWPDotNet: false
      # For mrtk_pr builds, validation scripts (code and docs) should be scoped to only
      # the set of changed files, so that we can save some time. There's no need to
      # check unchanged files for code style/doc style violations.
      scopedValidation: true
      # This particular job shouldn't run tests (they happen in PRValidationTest)
      runTests: true
      UnityVersion: $(Unity2018Version)

  - template: templates/end.yml
- job: PRValidationTest
  timeoutInMinutes: 20
  pool:
    name: On-Prem Unity
    demands:
    - Unity2018.4.6f1
    - COG-UnityCache-WUS2-01
    - SDK_18362 -equals TRUE
  steps:
  - template: templates/common.yml
    parameters:
      # The only task that this job should do is run the tests.
      # Building is handled by PRValidationBuild.
      runTests: true
      buildStandalone: false
      buildUWPX86: false
      buildUWPArm: false
      buildUWPDotNet: false
      validateCode: false
      UnityVersion: $(Unity2018Version)
  - template: templates/end.yml