# Build for PR validation.

variables:
  UnityVersion: Unity2018.3.7f1
  MRTKVersion: 2.0.0

pool:
  name: On-Prem Unity
  demands:
  - Unity2018.3.7f1

jobs:
- job: PR validation build
  timeoutInMinutes: 90
  steps:
  - template: templates/common.yml
  - template: templates/end.yml
